---
Name: fromholdio-bouncer
After:
  - 'socialmeta'
  - 'cmsstickymenupreference'
  - 'cmspreviewpreference'
  - 'session-manager'
---

SilverStripe\Security\Member:
  extensions:
    - Fromholdio\Bouncer\Extensions\MemberExtension

Fromholdio\Bouncer\Admin\MembersAdmin:
  menu_priority: 70

Fromholdio\Bouncer\Admin\GroupsAdmin:
  menu_priority: 60

Fromholdio\Bouncer\Admin\AccessAdmin:
  menu_priority: 50

SilverStripe\Admin\SecurityAdmin:
  menu_priority: -50
  menu_icon_class: 'font-icon-cog'

SilverStripe\Admin\LeftAndMain:
  menu_groups:
    Security:
      icon: 'shield'
      children:
        - Fromholdio-Bouncer-Admin-MembersAdmin
        - Fromholdio-Bouncer-Admin-GroupsAdmin
        - Fromholdio-Bouncer-Admin-AccessAdmin
        - SilverStripe-Admin-SecurityAdmin

---
Name: fromholdio-bouncer-groups
After:
  - 'fio-configured-groups'
---

SilverStripe\Security\Group:
  extensions:
    - Fromholdio\Bouncer\Extensions\GroupExtension
  configured_groups:
    administrators:
      title: Administrators
      sort: 0
      permissions:
        - ADMIN
    managers:
      title: Managers
      sort: 1
      permissions:
        - CMS_ACCESS_CMSMain
        - CMS_ACCESS_AssetAdmin
        - 'CMS_ACCESS_Fromholdio\Bouncer\Admin\GroupsAdmin'
        - 'CMS_ACCESS_Fromholdio\Bouncer\Admin\MembersAdmin'
        - EDIT_ACCESSCONFIG
        - FILE_EDIT_ALL
        - SITETREE_VIEW_ALL
        - SITETREE_EDIT_ALL
        - SITETREE_REORGANISE
        - VIEW_DRAFT_CONTENT
        - CMS_ACCESS_SecurityAdmin
        - EDIT_PERMISSIONS
        - SITETREE_GRANT_ACCESS
        - EDIT_SITECONFIG
    editors:
      title: Editors
      sort: 2
      permissions:
        - CMS_ACCESS_CMSMain
        - CMS_ACCESS_AssetAdmin
        - FILE_EDIT_ALL
        - SITETREE_VIEW_ALL
        - SITETREE_EDIT_ALL
        - SITETREE_REORGANISE
        - VIEW_DRAFT_CONTENT
    previewers:
      title: Previewers
      sort: 3
      permissions:
        - VIEW_DRAFT_CONTENT
